### ISSUE TITLE
version 1.2 Mac  wifi surveyor fail input string error

### ISSUE THREAD

**Issue by haz-ai** [ecoAPM/WiFiSurveyor#594]
fail: WiFiSurveyor[0]
      12/04/2022 10:03:55: The input string '91  7' was not in a correct format.
fail: WiFiSurveyor[0]
      12/04/2022 10:04:00: The input string '91  7' was not in a correct format.

**Comment by SteveDesmond-ca** [comment]
Thanks for the bug report.

Could you let me know which version of macOS you're on, and follow the steps in #157 to upload wi-fi data from the airport utility here?

Feel free to redact the SSID names if desired.

**Comment by haz-ai** [comment]
Issue fixed. Do not use a dns server such as pihole, causes faults and destroys airports default behaviours

**Comment by haz-ai** [comment]
ok so Issue came back, with different error, could it be that I am connected to a google wifi mesh network, also all xxxxx are my network, the other networks have been renamed with different characters

**Comment by SteveDesmond-ca** [comment]
Thanks for that airport output file. The file was successfully parsed, so I think the redactions removed some vital information.

My intuition is telling me that some SSID has multi-byte characters, which is affecting the tabular output if macOS isn't accounting for this. Based on the error in the original message, I think it's the one on channel 7 (where the `91  7` is actually the signal strength and the channel, offset by 4 bytes). I was able to reproduce this by replacing 4 `y`s in the redacted file with a single 😃 emoji.

The signal is low enough that it probably only sometimes appears, which is why the error is intermittent. A full solution will require an unredacted airport output that includes the SSID in question, which you can email privately to `steve (at) ecoAPM (dot) com` if preferred.

In the meantime, I'll get a patch release out that ignores (and warns in the console about) individual unparseable access points.

Thanks again for your help with this edge case!

**Comment by SteveDesmond-ca** [comment]
Thanks for the unredacted file, @haz-ai -- indeed, as suspected, there is an emoji in one of the SSIDs, which is breaking the tabular structure. I already have a proposed fix, it just needs some further testing, and I should have a v1.2.1 out within a couple days.

**Comment by haz-ai** [comment]
All good
Gotta love people breaking standards. Routers really shouldn’t allow
emoji’s or spaces to exist as it kills some old devices.
And no rush about it
